---
- name: Set state stopped for {{ anarchy_subject_name }}
  anarchy_subject_update:
    metadata:
      labels:
        state: stopped
    spec:
      vars:
        current_state: stopped
    status:
      towerJobs:
        stop:
          completeTimestamp: '{{ anarchy_run_timestamp }}'

- name: Mark stop complete
  anarchy_complete_action: {}
...
