---
- name: Run action based on current_state and desired_state
  vars:
    _current_state: "{{ current_state | default('unknown') }}"
    _desired_state: "{{ desired_state | default('unknown') }}"
    _action: >-
      {{ 'provision' if _current_state == 'new' else
         'start' if (_current_state == 'stopped' and _desired_state == 'started') else
         'stop' if (_current_state == 'started' and _desired_state == 'stopped') else
         'no action' }}
  when: _action != 'no action'
  block:
  - name: Schedule {{ _action }} for {{ anarchy_subject_name }}
    anarchy_schedule_action:
      action: "{{ _action }}"

  - name: Set {{ anarchy_subject_name }} current state to {{ _action }}-pending
    anarchy_subject_update:
      skip_update_processing: true
      metadata:
        labels:
          state: "{{ _action }}-pending"
      spec:
        vars:
          current_state: "{{ _action }}-pending"

- name: Run action based on current_state and desired_state
  when: check_status | default(false) | bool
  block:
  - name: Schedule status check for {{ anarchy_subject_name }}
    anarchy_schedule_action:
      action: status

  - name: Set {{ anarchy_subject_name }} check_status to false
    anarchy_subject_update:
      skip_update_processing: true
      spec:
        vars:
          check_status: false
