---
- name: Schedule {{ _action }} for {{ anarchy_subject_name }}
  vars:
    _current_state: "{{ current_state | default('unknown') }}"
    _desired_state: "{{ desired_state | default('unknown') }}"
    _action: >-
      {{ 'provision' if _current_state == 'provision-pending' else
         'start' if (_current_state == 'stopped' and _desired_state == 'started') else
         'stop' if (_current_state == 'started' and _desired_state == 'stopped') else
         'no action' }}
  when: _action != 'no action'
  anarchy_schedule_action:
    action: "{{ _action }}"
