---
- name: Provision {{ anarchy_subject_name }}
  when: check_status_state == "pending"
  include_tasks: run-status.yaml

- name: Check provision of {{ anarchy_subject_name }}
  when: check_status_state == "running"
  vars:
    tower_job_action: status
    tower_job_info: "{{ vars.anarchy_subject.status.towerJobs.status }}"
  include_tasks: check-deployer-job.yaml
...
