---
- name: Immediately remove finalizers on {{ anarchy_subject_name }} if never provisioned
  when: vars.anarchy_subject.status.towerJobs.provision.deployerJob | default('') == ''
  anarchy_subject_delete:
    remove_finalizers: true

- name: Schedule destroy {{ anarchy_subject_name }}
  when: vars.anarchy_subject.status.towerJobs.provision.deployerJob | default('') != ''
  anarchy_schedule_action:
    action: destroy
...
