---
- name: Set {{ anarchy_subject_name }} current state to provision-pending
  anarchy_subject_update:
    metadata:
      labels:
        state: provision-pending
    spec:
      vars:
        current_state: provision-pending
        job_vars:
          uuid: >-
            {{ vars.anarchy_subject.vars.job_vars.uuid | default((2*127) | random | to_uuid) }}
