---

# TODO: Remove this debug message
- name: DEBUG MESSAGE
  debug:
    msg:
      - "#############################################"
      - "DEBUG MESSAGE"
      - "#############################################"
      - "Current State: {{ current_state | default('unknown') }}"
      - "Desired State: {{ desired_state | default('unknown') }}"
      - "Current Job Vars: {{ vars.anarchy_subject.vars.job_vars | default('unknown') }}"
      - "Previous Job Vars: {{ vars.anarchy_subject_previous_state.spec.vars.job_vars | default('unknown') }}"

- name: Run action based on current_state and desired_state
  vars:
    _current_state: "{{ current_state | default('unknown') }}"
    _desired_state: "{{ desired_state | default('unknown') }}"
    _action: >-
      {{
        'provision' if _current_state == 'new' else
        'start' if (_current_state == 'stopped' and _desired_state == 'started') else
        'stop' if (_current_state == 'started' and _desired_state == 'stopped') else
        'update' if (vars.anarchy_subject.vars.job_vars != (vars.anarchy_subject_previous_state.spec.vars.job_vars | default(vars.anarchy_subject.vars.job_vars))) else
        'no action'
      }}
  when: _action != 'no action'
  block:
  - name: Set {{ anarchy_subject_name }} current state to {{ _action }}-pending
    anarchy_subject_update:
      skip_update_processing: true
      metadata:
        labels:
          state: "{{ _action }}-pending"
      spec:
        vars:
          current_state: "{{ _action }}-pending"

  - name: Schedule {{ _action }} for {{ anarchy_subject_name }}
    anarchy_schedule_action:
      action: "{{ _action }}"

- name: Run action based on current_state and desired_state
  when: check_status_state == 'pending'
  block:
  - name: Set {{ anarchy_subject_name }} check_status to false
    anarchy_subject_update:
      skip_update_processing: true
      spec:
        vars:
          check_status_state: pending

  - name: Schedule status check for {{ anarchy_subject_name }}
    anarchy_schedule_action:
      action: status
...
