---
- name: Set state starting for {{ anarchy_subject_name }}
  anarchy_subject_update:
    skip_update_processing: true
    metadata:
      labels:
        state: starting
    spec:
      vars:
        current_state: starting
    status:
      towerJobs:
        start:
          deployerJob: '{{ anarchy_action_callback_data.data.id | default(None) }}'
          deployerTimestamp: '{{ anarchy_run_timestamp }}'
