---
- name: Provision {{ anarchy_subject_name }}
  when: current_state == "provision-pending"
  include_tasks: run-provision.yaml

- name: Check provision of {{ anarchy_subject_name }}
  when: current_state == "provisioning"
  vars:
    tower_job_action: provision
    tower_job_info: "{{ vars.anarchy_subject.status.tower_jobs.provision }}"
  include_tasks: check-deployer-job.yaml
...
