---
- name: Set state stopping for {{ anarchy_subject_name }}
  anarchy_subject_update:
    metadata:
      labels:
        state: stopping
    spec:
      vars:
        current_state: stopping
    status:
      towerJobs:
        stop:
          deployerJob: '{{ anarchy_action_callback_data.data.id | default(None) }}'
          deployerTimestamp: '{{ anarchy_run_timestamp }}'

- when:
  - poolboy_resource_handle_name != ''
  - poolboy_resource_handle_namespace != ''
  name: Set desired_state stopped in resource handle for {{ anarchy_subject_name }}
  # FIXME - switch to k8s_json_patch module?
  command: >-
    oc patch resourcehandles.poolboy.gpte.redhat.com --type=json
    -n {{ poolboy_resource_handle_namespace | quote }}
    {{ poolboy_resource_handle_name | quote }}
    --patch={{ json_patch | to_json | quote }}
  vars:
    json_patch:
    - op: replace
      path: /spec/resources/{{ poolboy_resource_index }}/template/spec/vars/desired_state
      value: stopped
  # This is best-effort, don't fail on task failure
  ignore_errors: true

- when:
  - poolboy_resource_claim_name != ''
  - poolboy_resource_claim_namespace != ''
  # FIXME - switch to k8s_json_patch module?
  name: Set desired_state stopped in resource claim for {{ anarchy_subject_name }}
  command: >-
    oc patch resourceclaims.poolboy.gpte.redhat.com --type=json
    -n {{ poolboy_resource_claim_namespace | quote }}
    {{ poolboy_resource_claim_name | quote }}
    --patch={{ json_patch | to_json | quote }}
  vars:
    json_patch:
    - op: replace
      path: /spec/resources/{{ poolboy_resource_index }}/template/spec/vars/desired_state
      value: stopped
  # This is best-effort, don't fail on task failure
  ignore_errors: true
