---
- name: Run deployer start {{ anarchy_subject_name }}
  vars:
    new_subject_state: starting
    tower_job_template_playbook: >-
      {{ vars.anarchy_governor.vars.job_vars.__meta__.deployer.entry_points.start
       | default(vars.anarchy_governor.vars.job_vars.__meta__.deployer.entry_point)
       | default('ansible/lifecycle_entry_point.yml') }}
    tower_job_extra_vars: >-
      {{ vars.anarchy_subject.vars.job_vars | default({})
       | combine(vars.anarchy_governor.vars.job_vars, recursive=True)
       | combine(vars.dynamic_job_vars, recursive=True)
       | combine({
         "ACTION": "start",
         callback_url_var: anarchy_action_callback_url,
         callback_token_var: anarchy_action_callback_token,
       }, recursive=True)
      }}
  include_tasks:
    file: check-run-tower-job.yaml

- name: Schedule check for start of {{ anarchy_subject_name }}
  anarchy_continue_action:
    after: "{{ tower_job_check_interval }}"
...
